version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    target-branch: "docker"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "docker"
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "daily"
    target-branch: "docker"
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "docker"
