version: "3.9"
services:
  client_web:
    build: ./client
    ports:
      - "8081:8081"
    container_name: client-prod
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - PORT=8081
      - REACT_APP_API_URL=${API_URL:-http://localhost:8080}
      - REACT_APP_CALLBACK_URL=${CALLBACK_URL:-http://localhost:8081}
      - HTTPS=${HTTPS:-false}
      - SSL_CRT_FILE=${SSL_CRT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
  server:
    build: ./server
    ports:
      - "8080:8080"
      - "443:8080"
    container_name: server-prod
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=8080
      - URL_MONGO=mongodb://user_area:pass_area@mongo
      - HTTPS=${HTTPS:-false}
      - SSL_CRT_FILE=${SSL_CRT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
      - BASE_URL=${BASE_URL:-http://localhost}
      - TWITTER_APP_ID=${TWITTER_APP_ID:-pxeTacjpO5tTbBnvy7aYzC3UF}
      - TWITTER_APP_SECRET=${TWITTER_APP_SECRET:-LK4zIBmTPqvn36egbtP9HmJ6NrfHBFudHCC0PjV7iBB15tmyKD}
      - REDDIT_APP_ID=${REDDIT_APP_ID:-isUVYO3_2jTORpYN_SVSZA}
      - REDDIT_APP_SECRET=${REDDIT_APP_SECRET:-3X7O0lsVJ5HjWE3YC2QB7OBKZxOXtQ}
      - TWITCH_APP_ID=${TWITCH_APP_ID:-vi9za74j91x41dxvhmdsyjzau002xe}
      - TWITCH_APP_SECRET=${TWITCH_APP_SECRET:-wteackfgzu4nqmj72azqg5bts4rduq}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-257681430348-9r8vob0chstjb5to7atf9mr25fllnvkv.apps.googleusercontent.com}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-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}
      - SPOTIFY_APP_ID=${SPOTIFY_APP_ID:-27c89047c1a5470a972174a1f19b54c4}
      - SPOTIFY_APP_SECRET=${SPOTIFY_APP_SECRET:-b1c0e71d34dd4b3f858561bc2d3ab229}
      - WEBHOOK_URL=${WEBHOOK_URL:-inserer_url_ici}

  mongo:
    container_name: mongo-prod
    image: mongo:4.4.6
    restart: always
    logging:
      driver: none
    volumes:
      - "./mongo/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_area
      MONGO_INITDB_ROOT_PASSWORD: pass_area
