version: "3.9"
services:
  client:
    build: ./client/Dockerfile.dev
    ports:
      - 8081:8081
    container_name: client-prod
    volumes:
      - ./client/:/app
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 8080:8080
    container_name: server-prod