version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "8081:8081"
    container_name: client-prod
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "8080:8080"
      - "443:8080"
    container_name: server-prod
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://user_area:pass_area@mongo
      - PORT=8080

  mongo:
    image: mongo:4.4.6
    restart: always
    container_name: mongo-prod
    logging:
      driver: none
    volumes:
      - "./mongo/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_area
      MONGO_INITDB_ROOT_PASSWORD: pass_area