version: "3.9"
services:
  client_web:
    build: ./client
    ports:
      - "8081:8081"
    container_name: client-prod
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - PORT=8081
      - REACT_APP_API_URL=${API_URL:-http://localhost:8080}
      - REACT_APP_CALLBACK_URL=${CALLBACK_URL:-http://localhost:8081}
      - HTTPS=${HTTPS:-false}
      - SSL_CRT_FILE=${SSL_CRT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
  server:
    build: ./server
    ports:
      - "8080:8080"
      - "443:8080"
    container_name: server-prod
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=8080
      - URL_MONGO=mongodb://user_area:pass_area@mongo
      - HTTPS=${HTTPS:-false}
      - SSL_CRT_FILE=${SSL_CRT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
      - BASE_URL=${BASE_URL:-http://localhost}
      - TWITTER_APP_ID=${TWITTER_APP_ID:-8uDiSmBXliIrxodHw6mwuaJyh}
      - TWITTER_APP_SECRET=${TWITTER_APP_SECRET:-NOtO3KLwKFeXm6YuH4wiM5qtzUAi87sUiYD6piZc5jjOP4Ip4k}
      - REDDIT_APP_ID=${REDDIT_APP_ID:-isUVYO3_2jTORpYN_SVSZA}
      - REDDIT_APP_SECRET=${REDDIT_APP_SECRET:-3X7O0lsVJ5HjWE3YC2QB7OBKZxOXtQ}
      - TWITCH_APP_ID=${TWITCH_APP_ID:-vi9za74j91x41dxvhmdsyjzau002xe}
      - TWITCH_APP_SECRET=${TWITCH_APP_SECRET:-5f9xt5qhr8ly2n84q4qwxb7ocac38z}

  mongo:
    container_name: mongo-prod
    image: mongo:4.4.6
    restart: always
    logging:
      driver: none
    volumes:
      - "./mongo/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_area
      MONGO_INITDB_ROOT_PASSWORD: pass_area
