version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    container_name: client-dev
    volumes:
      - ./client/:/app
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    container_name: server-dev
    volumes:
      - ./server/:/app
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://user_area:pass_area@mongo

  mongo:
    container_name: mongo-dev
    image: mongo
    restart: always
    logging:
      driver: none
    volumes:
      - "./mongo/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_area
      MONGO_INITDB_ROOT_PASSWORD: pass_area