name: testing

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: linuxserver/docker-compose
    steps:
      - uses: actions/checkout@v3
      - name: Build docker-compose
        run: docker-compose up -d
      - name: Sleep for 15 seconds
        run: sleep 15
        shell: bash
      - name: Test client
        run: curl localhost:8081
      - name: Test server
        run: curl localhost:8080/ping2
